language: node_js

node_js:
  # - '0.10'
  # - '0.12'
  # - '4.0'
  # - '4.1'
  - '4.2'
  # - '5.0'

# before_install:
  # - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  # - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  # - sudo apt-get update -qq
  # - sudo apt-get install -qq google-chrome-stable

install:
  - npm install
  - npm run install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run test-travis-ci

notifications:
  slack:
    rooms:
    - secure: "MPlmBk2refAIYxG0pWalcTNJwmlhh/W0/5phB3xEoLl/r1hx1w81cUuQCgnmEN7+V0PgFAIafHxxmMYncHSzTZyM9pNrz2ZBp1xQWskLdHYVfOaXwwzp0SzQo95oTW26a0xKE+IRSNln4UbzEKAHhzWn+je1byZZv3TlG/NER2xVMjYM5i4wTmeHc5khsGzEga8pr7mUSToQvOZ1YBZcvIvauZ6zdEq4wV+zWOwU1UPTy4/EGzIh9pRThz5grDFIo82E7lNiMAMWRUESbB98Eq00pcg65m7VLA7bkSD4mpDG++buBX7ag9bdKpxymyGRBESf82nBZf8t7/LWlZdToXdnqAK9KLbM7Js7UVDBINKI99/KyQItqOPETk4n/EGFPY0PdvQCJ4TpEYA/60W3G2z2DJdFCbf4kiPEYuoO5qAo6/gS9Ra1rodTw5oylV9GgduQS//yqhaoSBAoQZu1BVw0eH5a7EQiSKLBk8DIYChwotHERdG85Owr9/BxeYchReHdyIJscS+qLagYdUS9CCk48Nn5m6PSpdxBKisPbSxTPYVEa4/xo6T7Obc+PB+7GM9NT04d9PURVaXADOoeTik8aoTO2kxz2vYptj5RV5xiNu9zf+87l1HGfzp3uC8BV4yqWZ4wC9tXNkdTUauJRBbI92PZXQvzLxk7p9w5Js8="
